name: Build and Publish Docker By Andy test3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: andychan516/docker-githubaction
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
